apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: ecsmonitoring-metrics
  namespace: esx-system
spec:
  metrics-collection:
    enabled: true
    metrics-sink:
      url: "http://10.212.2.182:30778/api/v1/write"
      data-format: "prometheusremotewrite"